version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main

jobs:
  build:
    working_directory: ~/DevOpsApplication
    docker:
      - image: cimg/node:20.17.0  # Use cimg/node for a leaner, maintained image
    steps:
      - checkout  # Pull code first
      - run:
          name: Update npm
          command: sudo npm install -g npm@latest && npm -v  # Update npm and verify
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

  deploy:
    docker:
      - image: cimg/node:20.17.0
    steps:
      - run:
          name: Deploy Application
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@$EC2_PUBLIC_DNS "rm -rf DevOpsApplication; git clone https://github.com/devopsgroupca/DevOpsApplication.git; source DevOpsApplication/deploy.sh"
