version: 2.1

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main

jobs:
  build:
    working_directory: ~/ExampleApplication
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Update npm
          command: npm install -g npm@latest
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

  deploy:
    docker:
      - image: circleci/node:16
    steps:
      - run:
          name: Deploy application
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@$EC2_PUBLIC_DNS "
              rm -rf DevOpsApplication &&
              git clone https://github.com/DevOpsGroupCA/DevOpsApplication.git &&
              cd DevOpsApplication &&
              chmod +x deploy.sh &&
              ./deploy.sh
            "
